# Generated by Django 5.2.2 on 2025-09-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_formassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
