# Generated by Django 5.2.6 on 2025-09-29 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_submission_file_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clossform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_status', models.CharField(max_length=20)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.form')),
            ],
        ),
        migrations.DeleteModel(
            name='SubmissionFile',
        ),
    ]
